# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/salami/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),salami)

$(call add-radio-file-sha1-checked,radio/abl.img,bf1c3bc36fc15ec140926a04144265904bf30433)
$(call add-radio-file-sha1-checked,radio/aop.img,d11e57524950a8d882717b825f262d59c3647443)
$(call add-radio-file-sha1-checked,radio/aop_config.img,4f6fe07d1fa064670148b479fbf9c46073985076)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,495d087f2dd9ba8f29f703276b4b5e68e6ce1462)
$(call add-radio-file-sha1-checked,radio/cpucp.img,65e63b17c4d21f5f09c45303bf864271efd8a108)
$(call add-radio-file-sha1-checked,radio/devcfg.img,5f922461ecb1cbc2b0e20f261c989d83d3e9f8e5)
$(call add-radio-file-sha1-checked,radio/dsp.img,0cc5776825200ff66abc8606a52634c77b10e63d)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,70cdd139b1742bd8e3957309b2b90a887e8669af)
$(call add-radio-file-sha1-checked,radio/hyp.img,f0e62b045c5ae46d323d2bf487bb5a7cfa3e5d8d)
$(call add-radio-file-sha1-checked,radio/imagefv.img,35a4f9d3c594cde7e2b6ce781aafcd1cb90815fb)
$(call add-radio-file-sha1-checked,radio/keymaster.img,dcb5009e8eb45d609acc8862c06b7a5b505ac938)
$(call add-radio-file-sha1-checked,radio/modem.img,1f15419f4a17f53d7e6ccdc9f700e14d80d25d6d)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,1c584c7b98f32a7ccceebbad7564e3bc0944ccb0)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,dbd585e7ec7a50279952b46a665bcedf2d871f96)
$(call add-radio-file-sha1-checked,radio/qupfw.img,654b6eb44f2c460ad719317e128bb365961c1fc6)
$(call add-radio-file-sha1-checked,radio/shrm.img,e9df6a7aa0fc455e4a1df24e1a710e2bbed5eeeb)
$(call add-radio-file-sha1-checked,radio/splash.img,8877705066051214763727acd252d62aba94aa5e)
$(call add-radio-file-sha1-checked,radio/tz.img,a0b9c0d02675e6e893ce30c15bb2333006286127)
$(call add-radio-file-sha1-checked,radio/uefi.img,f9b5516e209cd8e29f20cf21bb3715f5d91f0c15)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,db1a6ed01b07561ae7841caf1c516f251082ac7b)
$(call add-radio-file-sha1-checked,radio/xbl.img,23a9baf2501685b7da926b2e06b051b55c2c3412)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,210d761cab52f6718097d8477a25da364650c042)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,45ced57c835e10f5e508a560008b850d1d79812f)

endif
