# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/salami/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),salami)

$(call add-radio-file-sha1-checked,radio/abl.img,02cc2d7bf8e6019317e4d81f2d09a29d25f3635f)
$(call add-radio-file-sha1-checked,radio/aop.img,873b7c38389bda72359773e5d64b2fd2fae79b9a)
$(call add-radio-file-sha1-checked,radio/aop_config.img,7f8972830f7d8fa576b32d45566a4cc2196a802d)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,cd467b97eb9e628adb9a187a8710149627cbc23e)
$(call add-radio-file-sha1-checked,radio/cpucp.img,a922ef364b1c9f908a66df277d09be87f251c6f2)
$(call add-radio-file-sha1-checked,radio/devcfg.img,2e6fb041660118c7c68e2c7e3f688fff95a29a10)
$(call add-radio-file-sha1-checked,radio/dsp.img,0cc5776825200ff66abc8606a52634c77b10e63d)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,10ac34240e9c8c8e32c1a3d9e13b93d4911108c1)
$(call add-radio-file-sha1-checked,radio/hyp.img,59e2f51a5a70c9d11f32fe1e573e7e5a6a027913)
$(call add-radio-file-sha1-checked,radio/imagefv.img,4d92ce2b3141926ec0d026630b01195a1158c604)
$(call add-radio-file-sha1-checked,radio/keymaster.img,5efde5a263862938f8f2cd314b803ebc6ca099d2)
$(call add-radio-file-sha1-checked,radio/modem.img,3acde754cd1afae0d9dcae8efafa37c936c965c3)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,1c584c7b98f32a7ccceebbad7564e3bc0944ccb0)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,d29f51b51cbb9cc100de15dfacd2cf502b00929c)
$(call add-radio-file-sha1-checked,radio/qupfw.img,587e6d6fa17cc4f5ba5a68b485e1c08b8a25bf08)
$(call add-radio-file-sha1-checked,radio/shrm.img,4aa143b72622549723e3744e9a71b491bb3fb50c)
$(call add-radio-file-sha1-checked,radio/splash.img,8877705066051214763727acd252d62aba94aa5e)
$(call add-radio-file-sha1-checked,radio/tz.img,b9cba75004d14bdad62ea50f21d2a5fddcaf6697)
$(call add-radio-file-sha1-checked,radio/uefi.img,301e4c242347e1466b59a72cba5167a193c914f0)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,a1a2badbc6ed96241e25b60b0ec8c47d99624703)
$(call add-radio-file-sha1-checked,radio/xbl.img,efbdc8c3dbd8c67ae99782cc220f13babfc2c2a8)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,b7985155d30634d59bb8c941d09d97c1b643eed6)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,5ea39b255b0a1d9dca4b16a61b3eac8f25e983f0)

endif
