# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/salami/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),salami)

$(call add-radio-file-sha1-checked,radio/abl.img,4988355e1dcfc10b1137ba13d5ff1b4c0183870b)
$(call add-radio-file-sha1-checked,radio/aop.img,e114479c23cc5143bbab6eb4ca31dbb8a7dc29c4)
$(call add-radio-file-sha1-checked,radio/aop_config.img,8f575c393aedaaf9c759a6fb72d9b6fdfa46c458)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,b9fa2deacdbce1237a2cffcf9a0c6d9d2ded1b5b)
$(call add-radio-file-sha1-checked,radio/cpucp.img,426d9ddf2b6a3b3b99759e0dc8f3d2da50892d27)
$(call add-radio-file-sha1-checked,radio/devcfg.img,ecbf123ff9fef1cfbca736169e2d4cd3e80269c9)
$(call add-radio-file-sha1-checked,radio/dsp.img,0cc5776825200ff66abc8606a52634c77b10e63d)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,f0ee1032fc21eae7b4496da1f729ff62637b321d)
$(call add-radio-file-sha1-checked,radio/hyp.img,224cfd19cc0a1c7da0f63051f74be17e0771b23c)
$(call add-radio-file-sha1-checked,radio/imagefv.img,7ef3f807f7aa89569b76060fc5a70dd4f5326e30)
$(call add-radio-file-sha1-checked,radio/keymaster.img,b75e28b405d816d9afabcda9474e103a9f9b9a8e)
$(call add-radio-file-sha1-checked,radio/modem.img,0cd54833564816a4e1c7c48f4f3b28b3f51c0f06)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,1c584c7b98f32a7ccceebbad7564e3bc0944ccb0)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,a9935dd232e835a3d712263146069a472ff1091f)
$(call add-radio-file-sha1-checked,radio/qupfw.img,66427c75dc43b5a6cc6586b392da39df333e7118)
$(call add-radio-file-sha1-checked,radio/shrm.img,3a8f21c116f9732e0b6a7990b892f28e736bd394)
$(call add-radio-file-sha1-checked,radio/splash.img,8877705066051214763727acd252d62aba94aa5e)
$(call add-radio-file-sha1-checked,radio/tz.img,6990cc755234827049b270d23fe0748f7aff4710)
$(call add-radio-file-sha1-checked,radio/uefi.img,6986ade9c8e0319116c8a62cdd42e749ac346af7)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,32bad1866d76c8ab64fef48b078e188b5d0cf942)
$(call add-radio-file-sha1-checked,radio/xbl.img,1a57fb709b61d5e8d7aeb8eb00e8ddd6da8e32fe)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,7c2c451513e490e6102f68d24f86bcaf5434ab68)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,e1d685fda2eea160ce00d50e21edb34c10476cdd)

endif
